### ISSUE TITLE
Dialogue System

### ISSUE THREAD

**Issue by n8hopp** [PennyS8/Diverge#10]
Need to either find or implement this. There is 100% a plethora of dialogue systems we'll be able to find online, or at least a tutorial on how to make one. It should be easy to add and modify lines of dialogue.

**Comment by n8hopp** [comment]
Sophie found a dialogue system that should work great for us. @arcangel25 , mind sending a link or name of that asset on the Asset Library?

**Comment by arcangel25** [comment]
https://github.com/nathanhoad/godot_dialogue_manager
