### ISSUE TITLE
Queue free on AudioPlayer's timer

### ISSUE THREAD

**Issue by clarkm25** [PennyS8/Diverge#31]
Whenever you run on and off of the pressure plate to open the door, if you do it enough, a queue_free() occurs on a timer that no longer exists.

The player must go on and off of the pressure plate AT LEAST 3 times before it triggers.

**Comment by n8hopp** [comment]
![Image](https://github.com/user-attachments/assets/ddab9322-aee1-40f0-85cc-93aaa2ea2e99)
